### ISSUE TITLE
unable to load Monafter catching Ditto

### ISSUE THREAD

**Issue by yroc78** [Phaetec/pogo-cruncher#91]
## Thanks for contributing!
- Please enter some information which help us solving this issue.
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like (idk how to do that)

### Setup
- [ x] I am using the latest version of this tool
- [ x] Installed using Docker
- [ ] Installed via precompiled zip-Archive
- [ ] Cloned and locally built

### Description
Describe your problem here. pokemon don't load after catching Ditto.
sorry I'm not a dev. just a user with almost no idea what I'm doing.
program loads and lets me see other accounts without ditto but when it's added to users poke dex, no mon load to send away

**Comment by n2o** [comment]
Thanks for this issue. I'll try to reproduce this and try to fix it!

**Comment by fsfikke** [comment]
Same issue here. Don't know if it worked immediately before catching Ditto, but I have a Ditto and this is what I get: <img width="1190" alt="untitled" src="https://cloud.githubusercontent.com/assets/6105891/20632289/b1181d3c-b33c-11e6-9b29-c1fe70829972.png">

**Comment by yroc78** [comment]
@fsfikke that is exactly what happens for me. I have another account without Ditto and it still loads fine. must be something with him. it's weird

**Comment by fsfikke** [comment]
I can confirm Ditto is the problem. I transferred the only Ditto I had and now Pogo Cruncher works again.

**Comment by yroc78** [comment]
@fsfikke any other way to fix it? I just caught a good one lol

**Comment by n2o** [comment]
I will check our moveset file later. We think this is the problem because they introduced a new Move for Ditto

**Comment by n2o** [comment]
Fixed. I added some error handling when it comes to moves, which are currently not available in our database. Since I have no original Ditto and currently can't find relvant data of Ditto's moves, please help me by sending me the ID of its missing moves. They are now shown up in the list of your pokemon like this:

![image](https://cloud.githubusercontent.com/assets/1507474/20747488/9856e6d2-b6ea-11e6-977f-f5a2851b53a8.png)

Please send me the missing id, in this case: 2101, so that I can add this to our database.

Thanks for your help. A new docker image is in the pipeline and will soon be available. You can check the status [on this site](https://hub.docker.com/r/phaetec/pogo-cruncher/builds/).

**Comment by n2o** [comment]
I'll keep this open until you guys confirm that it is now working properly ;-)

**Comment by n2o** [comment]
I finally caught a Ditto! (I was raging during lunch, that I can't reproduce the error because I haven't caught one and told my collegues that I will now catch one. First Rattata, first pokeball, first own Ditto!).

But the error does not appear on my computer. I just pulled the latest docker image, started it and it works as expected... Control + Shift + I opens your developer tools with the tab "Console". It would be nice to see the output in your console.

**Comment by n2o** [comment]
Added the missing move for Ditto. @Wegi is going to build a new binary. Docker images are up to date, [check the status here](https://hub.docker.com/r/phaetec/pogo-cruncher/builds/).
Pull the latest version from Dockerhub: `docker pull phaetec/pogo-cruncher`. You should see something like this:

```
n2o@host ~ % docker pull phaetec/pogo-cruncher
Using default tag: latest
latest: Pulling from phaetec/pogo-cruncher
3690ec4760f9: Already exists 
cfdb77eb56b4: Already exists 
0d438913956e: Already exists 
c2ed66601f13: Already exists 
c237cd38eae0: Already exists 
ebae0a1fd5ae: Already exists 
c930b94a134f: Pull complete 
6d1a949a7727: Pull complete 
b37deae2074d: Pull complete 
d004f2971e6f: Pull complete 
f1aee37ff37e: Pull complete 
adca9294e79d: Pull complete 
Digest: sha256:d51e4aa02c02121735d8fd67d9f77361c06ac0d603ee49af51b9728c6ecb4f9e
Status: Downloaded newer image for phaetec/pogo-cruncher:latest
```

After this, the app version is printed to the console. Just for verification that you have the latest version installed:

![image](https://cloud.githubusercontent.com/assets/1507474/20792862/6c5124c8-b7c4-11e6-8e7f-4b18f2bed544.png)

**Comment by yroc78** [comment]
@n2o 
Using default tag: latest
latest: Pulling from phaetec/pogo-cruncher
Digest: sha256:d51e4aa02c02121735d8fd67d9f77361c06ac0d603ee49af51b9728c6ecb4f9e
Status: Image is up to date for phaetec/pogo-cruncher:latest
got that but the screen still doesn't load pokemon. 
what is JS? I'm very basic with this but happy to do what I can to help.
![screen shot 2](https://cloud.githubusercontent.com/assets/23737829/20796472/3cd1f1ca-b7a4-11e6-8ead-f859de13445b.jpg)

**Comment by n2o** [comment]
Okay, thanks. What's the output in your JS console?

**Comment by yroc78** [comment]
how do I get that info for you?

**Comment by n2o** [comment]
Cmd + Opt + I opens the Developer Tools on your Mac. Then you can open the Tab "Console", which shows these prints.

**Comment by yroc78** [comment]
@n2o 
this?
body > div.js-stale-session-flash.stale-session-flash.flash.flash-warn.flash-banner.d-none

**Comment by n2o** [comment]
Nope, you can find it here: 
![image](https://cloud.githubusercontent.com/assets/1507474/20796685/97e14a7e-b7d7-11e6-89c6-c9c366f76d85.png)

Tab: Console

**Comment by yroc78** [comment]
@n2o 
ok I think I got it.
there is a ton of data. here are the top few lines
 [  8.451s] [om.next] transacted '[(app/loading {:status true})], #uuid "354aff17-5e72-4850-84be-f5f4acfbf9b4"
cruncher.js:605  [ 28.492s] [om.next] transacted '[(status/niantic {:status true})], #uuid "3e3f2c0a-4f23-42d9-ade4-1ae383a984cf"
cruncher.js:605  [ 28.505s] [om.next] transacted '[(status/niantic {:status true})], #uuid "0209efd1-8cd4-40ff-936c-dc2f8b12dd32"
cruncher.js:605  [ 38.932s] [om.next] transacted '[(app/loading {:status false})], #uuid "988086db-22df-4238-aa23-01535e4b632a"
cruncher.js:605  [ 38.938s] [om.next] transacted '[(update/error {:message nil})], #uuid "0a614de2-247f-4a3f-bd3a-2973bc4f927d"
cruncher.js:605  [ 38.941s] [om.next] transacted '[(user/logged-in {:status true})], #uuid "8aef3644-7e7c-4f14-a281-a53ac02a3c8a"
cruncher.js:605  [ 38.943s] [om.next] transacted '[(app/loading {:status true})], #uuid "b9e5bac1-46d9-4850-b008-32821661994f"
cruncher.js:605  [ 38.948s] [om.next] transacted '[(app/loading {:status true})], #uuid "a582e6fa-4fa4-44c9-947a-f234801f7f91"
cruncher.js:605  [ 38.956s] [om.next] transacted '[(change/view {:view :default})], #uuid "37fe37b9-b009-4d58-a01c-b7182b519485"
cruncher.js:605  [ 43.362s] [om.next] transacted '[(app/loading {:status false})], #uuid "9781c17a-f4a2-443c-a387-e2b84891555a"
cruncher.js:605  [ 43.842s] [om.next] transacted '[(update/error {:message nil})], #uuid "87ed9002-03cf-4d6e-b715-e0a51010ed73"
cruncher.js:605  [ 43.981s] [om.next] transacted '[(update/pokemon {:pokemon

**Comment by n2o** [comment]
Yes, that's really much. Thanks! Could you please paste everything from this to hastebin.com and provide the link? The critical position is still missing in your snippet. If you start from the beginning and don't click anything, we'd have a minimum output needed to locate the error.

Thanks for your help!

**Comment by yroc78** [comment]
@n2o 
let me know if this works
http://hastebin.com/moyuyazitu.rb

**Comment by n2o** [comment]
Awesome! I will use this data in my local testserver to reproduce your error this evening.

**Comment by yroc78** [comment]
@n2o 
this my be even more useful
http://hastebin.com/liyokugove.rb

**Comment by yroc78** [comment]
got it to work today! so far so good :-D

**Comment by n2o** [comment]
Nice. I got some positive feedback from some other guys who had the same problem. So I will close this issue.

**Comment by yroc78** [comment]
Works great now. not  sure what changed  but it's back to good now.
